# Generated by Django 4.1.7 on 2023-03-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_p_img.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='default_p_img.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(default='default_p_img.jpg', null=True, upload_to='images/'),
        ),
    ]
