# Generated by Django 4.1.7 on 2023-03-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_number',
            new_name='freelancer_key',
        ),
    ]
