# Generated by Django 4.1.7 on 2023-03-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
