# Generated by Django 4.1.7 on 2023-03-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
