# Generated by Django 4.1.7 on 2023-03-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_post_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='delivery_time',
            field=models.CharField(choices=[('1 día', '1 día'), ('2 días', '2 días'), ('3 días', '3 días'), ('4 días', '4 días'), ('5 días', '5 días'), ('6 días', '6 días'), ('1 semana', '1 semana'), ('2 semanas', '2 semanas'), ('3 semanas', '3 semanas'), ('1 mes', '1 mes'), ('2 meses', '2 meses')], default='1 día', max_length=20),
        ),
    ]
