# Generated by Django 4.1.7 on 2023-04-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_post_quantity_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
